export default [
    'ackbar.png',
    'boba - fett.png',
    'c3p0.png',
    'chewbacca.png',
    'clone - trooper.png',
    'darth - maul.png',
    'darth - vader.png',
    'emperor - palpatine.png',
    'ewok.png',
    'greedo.png',
    'han - solo.png',
    'jabba.png',
    'jango - fett.png',
    'jawa.png',
    'lando.png',
    'leia.png',
    'lightsaber - darth - vader.png',
    'lightsaber - luke - rotj.png',
    'lightsaber - luke.png',
    'lobot.png',
    'luke - skywalker.png',
    'obiwan - kenobi.png',
    'qui - gon - jinn.png',
    'r2d2.png',
    'red - five.png',
    'stormtrooper.png',
    'tusken - raider.png',
    'yoda.png',
]